version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'

  server:
    build: ./server
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/mydb"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
